

### mybatis configure
mybatis:
  type-aliases-package: com.diudiu.applet
  mapper-locations: classpath*:com/diudiu/applet/mapper/xml/*.xml
  configuration:
    lazy-loading-enabled: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/diudiu?useSSL=false&characterEncoding=utf-8&autoReconnect
      username: root
      password: daocao
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: false
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 25200000
      filters: slf4j,config
      #spring.datasource.druid.connection-properties=config.decrypt=true;config.decrypt.key=${jdbc.publickey}
      filter:
        slf4j:
          connection-log-enabled: false
          statement-log-enabled: false
          result-set-log-enabled: false
          statement-executable-sql-log-enable: true
server:
  port: 19990


### Jwt token configure
jwt:
  token:
    rsa-pri: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAK4RHGivu/z/wMEKVknsCo+LkYekl9o6y3zYSJPkxBfXyWqCJgeBSTPf25xaXwi2Jy8R4JFlGTEdFfv1QjZVSIQHTHo3fym8p8vAZSa0K25KLYnaZI4SYDS8fV2Q+9CRDdQmWVGfZ5kC3rGXHjWhpTMQWRtj5LGSTlfL6+XXePprAgMBAAECgYBI+qmThqJlh4D0LnZRFeKznkuMuEhmWaI5HKEJSK+iY3lx61EwclcTpbZ4jjcr+trg1Dj4HI/8VHqEIab6CrWU274Skh2psAcCIJjPZHxXIFxLqbEjXGBmi5B25lqKzJ2REEYzf3fdDAKolKcFqGEXItvJB6njdP9+YyzkrsHogQJBAOR6PT/ZWXiq2k7Akefl/pQycyjDouIMt5RB5YPrVK8rlBYaygBpm0ehthSPVthRJPADlzI/lJj9SvJHOnsLtkECQQDDCPZtcFrnWAOkulrafcUVkW9aevYTTmcRMQn+DP97W35sPvqmf4mgJb/9qA0IHf5rI9lfvuRRqOU/R0wBiP2rAkEAvDKQhypij4m0XxAyXyFNDQdtYlObtLWi9eU9x+ctj0jHJ1oTsDlNJbjngZH8iBx235kljsdegJKLjHvtiPNBwQJAcAqpDou6HSbJyQspgFU6MD7BWphC3ypuOUkTtXegGSyhfuvbMGUaGf81wTGWcvBQJRqOGNvf7C17rRN3TXZ2SwJAaNhjYA62IO4/nC1a4l6sig7ToDdYugr5NCJjLgHfOok1ajDDnKND+jSjMJBgCYjRscWnIc/TdE/EmNSLPU2ZSQ==
    rsa-pub: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCuERxor7v8/8DBClZJ7AqPi5GHpJfaOst82EiT5MQX18lqgiYHgUkz39ucWl8IticvEeCRZRkxHRX79UI2VUiEB0x6N38pvKfLwGUmtCtuSi2J2mSOEmA0vH1dkPvQkQ3UJllRn2eZAt6xlx41oaUzEFkbY+Sxkk5Xy+vl13j6awIDAQAB

### project configure
config:
  wechat:
    appid: 1
    secret: 2
    mchId: 3
    paySecret: 4